language: node_js

matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      language: node_js
      node_js: 7

before_install:
- printenv
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
  brew update > /dev/null;
  gem install --no-rdoc --no-ri cocoapods;
  fi

install:
- npm i -g cordova ionic@latest

script:
- npm ls -g --depth=0
- ./build.sh

